name: Sqitch Dynamic Multi-Schema CI/CD

on:
  push:
    paths:
      - 'schema*/**'

jobs:
  resolve-order:
    runs-on: ubuntu-latest
    outputs:
      deployment_order: ${{ steps.setorder.outputs.deployment_order }}
    steps:
      - uses: actions/checkout@v3
      - name: Resolve schema deployment order
        id: setorder
        run: |
          python3 scripts/resolve-dependency-order.py

  deploy:
    needs: resolve-order
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema: ${{ fromJson(needs.resolve-order.outputs.deployment_order) }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ${{ matrix.schema }}
        run: |
          cd ${{ matrix.schema }}
          sqitch deploy db:pg://$DB_USER:$DB_PASS@$DB_HOST/$DB_NAME
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
